# Generated by Django 4.2.2 on 2023-10-26 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0003_user_fotouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(help_text='Obligatorio. Digite su nemero de Cedula completo. Unicamente numeros. Sin puntos ni comas', max_length=11, unique=True, verbose_name='Cedula'),
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCoh', models.CharField(max_length=50, unique=True)),
                ('nombreCoh', models.CharField(max_length=100)),
                ('descrptionCoh', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delted', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
