# Generated by Django 4.2.2 on 2024-02-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0005_signature_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='nameSignature2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
