# Generated by Django 4.2.2 on 2024-02-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0006_alter_signature_namesignature2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fotouser',
        ),
    ]
