# Generated by Django 4.2.2 on 2024-02-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0007_remove_user_fotouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='nameSignature2',
        ),
    ]
