# Generated by Django 4.2.2 on 2024-02-28 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0008_remove_signature_namesignature2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='user',
            field=models.ForeignKey(limit_choices_to={'$or': [{'is_profesor': True}, {'is_Estudiante': True}]}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
