# Generated by Django 4.2.2 on 2024-02-29 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0009_alter_cohorte_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohorte',
            old_name='delted',
            new_name='deleted',
        ),
        migrations.RemoveField(
            model_name='cohorte',
            name='user',
        ),
        migrations.AddField(
            model_name='cohorte',
            name='user',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('is_Estudiante', True)), related_name='cohortes', to=settings.AUTH_USER_MODEL),
        ),
    ]
