# Generated by Django 4.2.2 on 2024-03-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0010_rename_delted_cohorte_deleted_remove_cohorte_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohorte',
            name='user',
        ),
    ]
