# Generated by Django 4.2.2 on 2024-03-01 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0011_remove_cohorte_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to=models.Q(('is_profesor', True)), related_name='cohortes', to=settings.AUTH_USER_MODEL, verbose_name='Profesores'),
        ),
    ]
