# Generated by Django 4.2.2 on 2024-03-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0012_cohorte_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohorte',
            old_name='deleted',
            new_name='delted',
        ),
        migrations.RemoveField(
            model_name='cohorte',
            name='teachers',
        ),
    ]
