# Generated by Django 4.2.2 on 2024-03-02 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0014_remove_cohorte_delted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='delted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
