# Generated by Django 4.2.2 on 2024-03-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0017_remove_cohorte_codigocoh_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signature',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
