# Generated by Django 4.2.2 on 2024-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0018_remove_profile_signature_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='status',
            field=models.CharField(choices=[('I', 'Innscripciónes Abiertas'), ('P', 'En Progreso'), ('F', 'Finalizado')], default='I', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, help_text='Obligatorio. Digite su nemero de Cedula completo. Unicamente numeros. Sin puntos ni comas', max_length=11, unique=True, verbose_name='Cedula'),
        ),
    ]
