# Generated by Django 4.2.2 on 2024-03-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0019_alter_cohorte_status_alter_user_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='status',
            field=models.CharField(choices=[('I', 'Inscripciónes Abiertas'), ('P', 'En Progreso'), ('F', 'Finalizado')], default='I', max_length=1, verbose_name='Estado'),
        ),
    ]
