# Generated by Django 4.2.2 on 2024-03-08 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0020_alter_cohorte_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('lecciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Learning.cohorte')),
                ('students', models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_Estudiante', True)), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
