# Generated by Django 4.2.2 on 2024-03-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0021_cursos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
