# Generated by Django 4.2.2 on 2024-03-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0022_delete_cursos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
