# Generated by Django 4.2.2 on 2024-03-10 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('field', models.FileField(blank=True, null=True, upload_to='archivos_adjuntos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota1')),
                ('mark2', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota2')),
                ('mark3', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota3')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='promedio')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tareas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
            },
        ),
    ]
