# Generated by Django 4.2.2 on 2024-03-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
